development:
  adapter: postgresql
  encoding: unicode
  database: mosserycodev
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mosserycotest
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mosserycoprod
  pool: 5
  password:  